[default]
FLASK_RUN_PORT=5000
EXTENSIONS = [
    'weather.ext.cors',
    'weather.ext.cache_config',
    'weather.views'
]

[development]
ENV = 'development'
DEBUG = true

[production]
ENV = "production"

[test]
ENV = 'testing'
DEBUG = false
TESTING = true
